	const String PAYMENT_CONTRACT_V1 = "paymentV1";
  const String METHOD_CREATE_PAYMENT     = "create_Payment";     // create intent (optional pre-auth)
	const String METHOD_AUTHORIZE_PAYMENT  = "authorize_Payment";  // hold funds
	const String METHOD_CAPTURE_PAYMENT    = "capture_Payment";    // settle funds (full/partial)
	const String METHOD_REFUND_PAYMENT     = "refund_Payment";     // refund (full/partial)
	const String METHOD_VOID_PAYMENT       = "void_Payment";       // release hold
	const String METHOD_DIRECT_PAY         = "direct_Pay";         // authorize + capture in one shot
	const String METHOD_PAUSE_PAYMENT      = "pause_Payment";
	const String METHOD_UNPAUSE_PAYMENT    = "unpause_Payment";
	const String HELP = "help";
  const String METHOD_GET_PAYMENT   = "get_Payment";
	const String METHOD_LIST_PAYMENTS = "list_Payments";
